revisionitems:
    label:  <<< TRANSLATE >>>
    view:
        list: ~/plugins/martin/blogrevisions/models/revisionlist/revisions-columns.yaml
    manage:
        form: ~/plugins/martin/blogrevisions/models/revisionlist/revisions-fields.yaml
        context: create